name: Publicar en PyPI

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  publicar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias de construcción
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Construir paquete
        run: python -m build

      - name: Publicar en PyPI
        uses: pypa/gh-action-pypi-publish@release/v1